### ISSUE TITLE
Requiring a .ts file from a .vue file seems to break with Webpack 2.1.0

### ISSUE THREAD

**Issue by icopp** [HerringtonDarkholme/vue-ts-loader#2]
This is using Webpack 2.1.0 (so the options are living inside of `new webpack.LoaderOptionsPlugin({options: {vue: {}}})` rather than root level of the webpack config) and vue-ts-loader 0.0.3.

It seems like my attempts to reference `.ts` files from `.vue` files (whether it's `lang="ts"` or not) reliably get one of two errors:

A default import (e.g. `import Whatever from './filename-without-extension'`):

```
ERROR in ./file/path/here.ts
Module build failed: TypeError: Cannot read property 'unsafeCache' of undefined
    at makeResolver (/path/to/project/node_modules/vue-ts-loader/resolver.js:35:57)
    at ensureTypeScriptInstance (/path/to/project/node_modules/vue-ts-loader/index.js:214:20)
    at Object.loader (/path/to/project/node_modules/vue-ts-loader/index.js:415:14)
```

A named import (e.g. `import {Whatever} from './filename-without-extension'`):

```
ERROR in ./file/path/here.ts
Module build failed: TypeError: Cannot read property 'getEmitOutput' of null
    at Object.loader (/path/to/project/node_modules/vue-ts-loader/index.js:444:33)
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./path/to/component.vue
 @ (nested component references here)
 ```

**Comment by HerringtonDarkholme** [comment]
Sorry for the late response. But I don't think vue-ts-loader is compatible with webpack2. And I didn't test it against webpack2 anyway.

I think ts-loader will support webpack2 when webpack2 officially release. Please use stable version for now. 

Also, ts-loader now has a `appendSuffix` option that does the same with vue-ts-loader. You probably should use ts-loader instead.

**Comment by HerringtonDarkholme** [comment]
ts-loader has officially supported webpack2. And vue-class-component has an official example for using ts-loader and vue-loader.
