### ISSUE TITLE
Is this library still required?

### ISSUE THREAD

**Issue by davidmoshal** [HerringtonDarkholme/vue-ts-loader#4]
referring to your comment:

https://github.com/vuejs/vue-class-component/issues/49

> Please use the official ts-loader. Vue support has been merged. https://github.com/TypeStrong/ts-loader#appendtssuffixto-regexp-default

However, this library is still included in your example:

https://github.com/HerringtonDarkholme/vue-ts-example

Thanks

**Comment by HerringtonDarkholme** [comment]
> Is this library still required?

No, you just need ts-loader.

**Comment by davidmoshal** [comment]
thanks, so in terms of setup, very close to `vue-class-component`, basically the same libraries with av-ts or vue-class-component.
