### ISSUE TITLE
Not working with newest version

### ISSUE THREAD

**Issue by John0x** [HerringtonDarkholme/vue-ts-loader#5]
Hey, this vue-ts-laoder does not seem to work with the newest vue version.
Can anyone confirm this?

**Comment by HerringtonDarkholme** [comment]
Please do provide a minimal reproduction. [Why is this required?](https://gist.github.com/Rich-Harris/88c5fc2ac6dc941b22e7996af05d70ff)

Also, I would recommend you to use the original ts-loader. vue-ts-loader exists for compatibility.

**Comment by John0x** [comment]
Is there a guide on using the original ts-loader with vue single-file-component and typescript?

Well, I've followed the guide basically and always get this error:
``
ERROR in ./~/ts-loader!./~/vue-loader/lib/selector.js?type=script&index=0!./src/pages/home/home.vue
Module build failed: Error: Could not find file: 'D:\dev\client\src\pages\home\home.vue'.
    at getValidSourceFile (D:\dev\client\node_modules\typescript\lib\typescript.js:79271:23)
    at Object.getEmitOutput (D:\dev\client\node_modules\typescript\lib\typescript.js:79638:30)
    at getEmit (D:\dev\client\node_modules\ts-loader\dist\index.js:99:43)
    at Object.loader (D:\dev\client\node_modules\ts-loader\dist\index.js:27:11)
 @ ./src/pages/home/home.vue 3:2-103
 @ ./src/app.router.ts
 @ ./src/app.js
 @ ./src/client-entry.js
 @ multi app
``

**Comment by John0x** [comment]
I got it working now. Had a problem with my loader config. But I'm still interested in your statement, that I should use ts-loader. The above mentioned error message prevents me from using ts-loader itself.
