### ISSUE TITLE
Does not work with webpack2

### ISSUE THREAD

**Issue by DmacMcgreg** [HerringtonDarkholme/vue-ts-loader#6]
By using
`vue: {
    loaders: {
      ts: 'vue-ts-loader'
    },
    // important for cooperating with vue-loader
    esModule: true
  },`

At the bottom of the config, the following error message is given:

WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'vue'. These properties are valid:
   object { amd?, bail?, cache?, context?, dependencies?, devServer?, devtool?, entry, externals?, loader?, module?, name?, node?, output?, performance?, plugins?, profile?, recordsInputPath?, recordsOutputPath?, recordsPath?, resolve?, resolveLoader?, stats?, target?, watch?, watchOptions? }
   For typos: please correct them.
   For loader options: webpack 2 no longer allows custom properties in configuration.

**Comment by vire** [comment]
You have to use for passing options to loader the [LoaderOptionsPlugin](https://webpack.js.org/plugins/loader-options-plugin/)  see https://webpack.js.org/guides/migrating/

`"vue"` prop can't be on you config object

**Comment by HerringtonDarkholme** [comment]
As @vire said, this is not vue-ts-loader's problem.

Also, you can use vanilla ts-loader. The feature in this repo has been merged.

**Comment by DmacMcgreg** [comment]
But it would be best to update the docs, no?

**Comment by jklmli** [comment]
Another weird quirk I ran into while setting up ts compilation in `.vue` files in webpack 2 - your js/ts script tags need to be written like this:
```html
<script lang="ts">
  ...
</script>
```
The value `ts` is dynamically used to look up the loader, so something like `typescript` won't work.
Luckily Intellij understands both 😛

**Comment by astroanu** [comment]
what is the exact way to migrate ??
