### ISSUE TITLE
allowJs:true, noEmit:false get compile fail while migrate from js to typescript in vue project

### ISSUE THREAD

**Issue by Hanruis** [HerringtonDarkholme/vue-ts-loader#7]
as the title said. I have a project that is migrating from js to ts. so there both js & ts file exist on my project.

while i use vue-ts-loader , and set `allowJs:true`, `noEmit:false` in tsconfig.json . it compiles fail and said that`error TS5055: Cannot write file 'xxx.js' because it would overwrite input file.` [reference resources](https://github.com/Microsoft/TypeScript/wiki/FAQ#why-am-i-getting-the-error-ts5055-cannot-write-file-xxxjs-because-it-would-overwrite-input-file-when-using-javascript-files)

**Comment by HerringtonDarkholme** [comment]
So as the link said, you need to set the outDir option.
Even it is ignored by webpack it needs to be set to convince compiler no file will be overwritten.

**Comment by Hanruis** [comment]
o ~~. outDir will be ignored by webpack... thx a lot
