### ISSUE TITLE
Is this project being retired in favor of ts-loader?

### ISSUE THREAD

**Issue by lucastheisen** [HerringtonDarkholme/vue-ts-loader#8]
I noticed that you are [contributing to ts-loader](https://github.com/TypeStrong/ts-loader/pull/448) which appears to be a direct competitor for the features provided by this module.  Everything seems to be changing rapidly right now, and I just wanted to make sure I am choosing the correct path...

**Comment by HerringtonDarkholme** [comment]
Just use ts-loader!

This module is created before ts-loader is actively maintained. This repo is here just for npm module.
